### ISSUE TITLE
Training with already searched policy.

### ISSUE THREAD

**Issue by qianwangn** [Jia-Research-Lab/SA-AutoAug#1]
The 6x schedule is too long for training. If I want to search augmentation policy in the first time and use the searched policy after, How can I do that?
@yanwei-li Thanks.

**Comment by yukang2017** [comment]
Hi,

The search don't need that long. You can follow maskrcnn-benchmark/search.sh for search. And then set cfg.AUTOAUG.LIST as your searched policy. And then train your model as the instructions in README.md.

Regards,
Chen Yukang
