### ISSUE TITLE
Translate set to (0, 0) in geometric _augs scripts

### ISSUE THREAD

**Issue by deepanshi-s** [Jia-Research-Lab/SA-AutoAug#10]
The translate variable to be used in the box-level geometric augmentations in the FCOS training scripts is set to (0, 0) here: https://github.com/dvlab-research/SA-AutoAug/blob/e69a0a841b00d638c65647c7efb5e3e1b782bad5/FCOS/fcos_core/augmentations/box_level_augs/geometric_augs.py#L35

**Comment by yukang2017** [comment]
Sorry for this typo. It is just for previously debug. I have fixed.
