### ISSUE TITLE
_box_aug_per_img函数中的归一化为什么是img = img + img_mean

### ISSUE THREAD

**Issue by HAOCHENYE** [Jia-Research-Lab/SA-AutoAug#2]
请问这是归一化操作么？看起来怪怪的。另外我看到zoom-out的代码里做了类似mosaic增强的操作，好像论文里没有提及？

**Comment by yukang2017** [comment]
你好，这个操作是因为torch里面那些颜色变换的函数要求的输入是[0, 1]之间，和训练时候数据的范围不一样。zoom-out那个操作是为了维持一下变换后图像大小还是那么大，所以就从一个pool里选了一些之前见过的图像做pad。

**Comment by HAOCHENYE** [comment]
欸，但是(img + img_mean )/ 255 不在0-1之间呀，img / 255才是吧？

**Comment by yukang2017** [comment]
因为我是在normalize之后加的这个aug，所以输入给aug的tensor已经减去了img_mean，所以需要给补回来。
https://github.com/dvlab-research/SA-AutoAug/blob/master/maskrcnn-benchmark/maskrcnn_benchmark/data/transforms/build.py#L43

**Comment by HAOCHENYE** [comment]
原来如此，多谢指教。

**Comment by yukang2017** [comment]
不客气。
