### ISSUE TITLE
Question about bounding boxes augmentation

### ISSUE THREAD

**Issue by Jasonlee1995** [Jia-Research-Lab/SA-AutoAug#4]
https://github.com/dvlab-research/SA-AutoAug/blob/master/FCOS/fcos_core/augmentations/box_level_augs/geometric_augs.py#L24

I saw the bounding box augmentation codes and I think there are some differences with AutoAugment-Det codes.

https://github.com/tensorflow/tpu/blob/3679ca6b979349dde6da7156be2528428b000c7c/models/official/detection/utils/autoaugment_utils.py#L505

What I understand is AutoAugment-Det implement translate_only_bbox as translate image patch with bounding box unchanged, but SA-AutoAug implement translate bounding boxes also image patches (there may be some redundant object cause of paste)

And just curious why just paste the image patches rather than translate the image patch?

There could be visual artifacts cause of paste on translation

**Comment by yukang2017** [comment]
Thanks for your good question. We do this for the following reasons:
1. If we only translate the image patch, there will leave a blank area on the original image patch, which might be harmful. Thus, we choose to keep the original image patch remained and paste a new one.
2. There will be more objects/samples for training, if we paste the image patches, which is beneficial.
