### ISSUE TITLE
Regarding the geometric bbox augmentation.

### ISSUE THREAD

**Issue by gkagkos** [Jia-Research-Lab/SA-AutoAug#7]
Hi, @yukang2017

On [this](https://github.com/dvlab-research/SA-AutoAug/blob/cb9403fe01cbd30d8b14bca106fd771586f1b89f/maskrcnn-benchmark/maskrcnn_benchmark/augmentations/box_level_augs/geometric_augs.py#L36) line of code you set the translation value to (0,0) even if you apply the translate augmentation.

That being said translate[0] + translate[1] != 0 will never be True. 

Is this the expected behaviour?

**Comment by yukang2017** [comment]
Hi gkagkos,

Thanks for the remind. I previously wrote this line for debug and forget to remove it. I have fixed it.
