### ISSUE TITLE
模型训练时使用的增强策略，参数和论文中的不一样

### ISSUE THREAD

**Issue by gfzwytc** [Jia-Research-Lab/SA-AutoAug#9]
感谢作者的伟大贡献，我在detectron2环境下训练了自己的数据集，训练时输出了使用的增强策略，发现和论文中的表9的增强策略有些不一样，这是为什么呢？
{'zoom_out': {'prob': 0.30000000000000004, 'level': 9}, 'zoom_in': {'prob': 0.25, 'level': 3}}
{'policies': 
[[('Color', 0.4, 2), ('translateX', 0.4, 4)],
 [('Brightness', 0.2, 4), ('rotate', 0.4, 2)], 
[('Sharpness', 0.4, 2), ('shearX', 0.2, 6)], 
 [('SolarizeAdd', 0.2, 2), **('hflip', 0.5, 1)**],
 [('Color', 0.0, 8), ('translateY', 0.2, 8)]], 
**'scale_ratios': {'area': [7, 5, 1], 'prob': [3, 3, 3]}}**
论文中的表9的增强策略
![image](https://user-images.githubusercontent.com/108044622/179336213-f4c6823e-6cfd-44ba-a7eb-58da3bb39fc7.png)

**Comment by yukang2017** [comment]
你好，我当时应该是进来了多次搜索，搜索到的结果会有所波动。两个策略其实差别非常小，我开源的时候找了个稳定性比较好的开源了。您也可以考虑改回文章中的那个，效果差不多的。

**Comment by gfzwytc** [comment]
> 你好，我当时应该是进来了多次搜索，搜索到的结果会有所波动。两个策略其实差别非常小，我开源的时候找了个稳定性比较好的开源了。您也可以考虑改回文章中的那个，效果差不多的。
